#!/usr/bin/env python
import sys
import random


def load_words(file_path):
    with open(file_path, 'r') as file:
        return file.read().splitlines()


def generate_xkcd_password(word_list, num_words=4, num_caps=0, num_numbers=0, num_symbols=0):
    if num_words < 4:
        num_words = 4

    words = random.sample(word_list, num_words)

    for i in range(num_caps):
        word_index = random.randint(0, num_words - 1)
        words[word_index] = words[word_index].capitalize()

    password = ''.join(words)

    numbers = ''.join(str(random.randint(0, 9)) for _ in range(num_numbers))
    symbols = ''.join(random.choice('~!@#$%^&*.:;') for _ in range(num_symbols))

    password = password + numbers + symbols

    return password


if __name__ == "__main__":
    dictionary_file = 'words.txt'  # Path to your dictionary file
    words = load_words(dictionary_file)

    args = sys.argv[1:]

    num_words = 4
    num_caps = 0
    num_numbers = 0
    num_symbols = 0

    while args:
        if args[0] == '-h':
            print("usage: xkcdpwgen [-h] [-w WORDS] [-c CAPS] [-n NUMBERS] [-s SYMBOLS]")
            print("Generate a secure, memorable password using the XKCD method")
            sys.exit(0)
        elif args[0] == '-w':
            num_words = int(args[1])
            args = args[2:]
        elif args[0] == '-c':
            num_caps = int(args[1])
            args = args[2:]
        elif args[0] == '-n':
            num_numbers = int(args[1])
            args = args[2:]
        elif args[0] == '-s':
            num_symbols = int(args[1])
            args = args[2:]
        else:
            args.pop(0)

    password = generate_xkcd_password(words, num_words, num_caps, num_numbers, num_symbols)

    print("Generated XKCD-style password:")
    print(password)
